### ISSUE TITLE
Add PR review conventions to Contributing.md

### ISSUE THREAD

**Issue by Aya-S** [python-sprints/pandas-mentoring#102]
PR rules:
input from two reviewers Is needed to merge a PR.
After one reviewer approves, the next reviewer can merge.
xref #70

**Comment by sara-02** [comment]
@Aya-S Can we expand the scope of this issue to include a general how to contribute section on the README?
Part 1: clone/fork/branch/add name to list
Part 2: Rules to PR review
PArt 3: claim existing issues  or add new issues, continue contributing.

**Comment by martinagvilas** [comment]
Maybe the README.md could point to the contributing.md and we could add all these things there, so to keep the README as introductory as possible?

**Comment by smiaa** [comment]
I concur with Martina, we shall have a link to contributing.md from
readme.md

**Comment by Aya-S** [comment]
A link to contributing.md does make sense

**Comment by sara-02** [comment]
Yes, it does.
Maybe something on the lines of 
https://github.com/pandas-dev/pandas/blob/master/.github/CONTRIBUTING.md
But modified to suit our group's need?

**Comment by martinagvilas** [comment]
That would be cool! We already have a contributing.md file in the root folder of our project (so we don't need to create one from scratch), but maybe we could add the information of the link you provided there @sara-02

**Comment by sara-02** [comment]
@martinagvilas second that.

**Comment by yomaokobiah** [comment]
Is anyone working on this at the moment?
> PArt 3: claim existing issues or add new issues, continue contributing.

@sara-02 did you mean the rules for taking over existing issues and how to add new issues?

**Comment by sara-02** [comment]
@Yomdroid Noone is working on this right now.
Yes, basic rules like:
Check the issue already exists, if open add your comment on it. If closed then reopen and add comments.
For new issues: Follow issue template,
for reporting errors, give details of the version/os you are running.

**Comment by yomaokobiah** [comment]
Thanks, I'll work on it.

**Comment by yomaokobiah** [comment]
For existing issues, how long does the person assigned to it have, before someone else can attempt to do it? @sara-02

**Comment by sara-02** [comment]
> For existing issues, how long does the person assigned to it have, before someone else can attempt to do it? @sara-02

Not aware of that, for the time being, we are just working on mutual agreement.

**Comment by datapythonista** [comment]
My opinion is that you can simply ping the person to see if it's still working or if they are happy that you take it. That could be somehow rude if you don't wait a reasonable time, but I think after few days, or a week or something that makes sense (depending on the context) that's perfectly fine.

**Comment by sara-02** [comment]
Fixed in #113 
@Aya-S feel free to open this issue in case you think more work needs to be done in the `contributing.md`.
