### ISSUE TITLE
Update NumFOCUS language in the pandas home page

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#111]
NumFOCUS (the non-profit that supports pandas), is asking all the projects to standardize the language we use about NumFOCUS. In pandas. we have the mention to NumFOCUS at the beginning of the home page pandas.pydata.org.

The requested text is next:
```
[Project Name] is a Sponsored Project of NumFOCUS, a 501(c)(3) nonprofit charity in the United States. NumFOCUS provides [Project Name] with fiscal, legal, and administrative support to help ensure the health and sustainability of the project. Visit numfocus.org for more information.

Donations to [Project Name] are managed by NumFOCUS. For donors in the United States, your gift is tax-deductible to the extent provided by law. As with any donation, you should consult with your tax adviser about your particular tax situation.
```

Note that `pandas` is used in lowecase even at the beginning of the sentence.

The website is in a separate repo: https://github.com/pandas-dev/pandas-website

**Comment by bhuvanakundumani** [comment]
I would love to work on this @datapythonista

**Comment by bhuvanakundumani** [comment]
@datapythonista - need clarification
Should the hyperlink for numfocus.org be 
https://numfocus.org/
or 
https://numfocus.org/sponsored-projects ( this is how it is in the current repo )

**Comment by datapythonista** [comment]
Thanks for taking this @bhuvanakundumani, the link should be to https://numfocus.org/.

It's also perfectly find to ask questions in the ticket, but if you prefer it's also perfectly fine to open PRs with your guess, since the PRs will be reviewed anyway. So don't feel the PR needs to be perfect, because having reviews and changing things is normal part of the workflow.

**Comment by bhuvanakundumani** [comment]
thanks for the clarification.

**Comment by datapythonista** [comment]
@bhuvanakundumani feel free to close this once you're ready.
