### ISSUE TITLE
Write simple installation instructions for pandas

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#114]
pandas has a quite complete documentation page with installation instructions:

https://pandas.pydata.org/pandas-docs/stable/install.html

But personally, I don't want users that come to pandas for the first time (and possibly to the whole PyData ecosystem) to find this document and have to use it to get started. I think it makes much more sense to provide a short document with how we think they should set everything up, and then a link to the existing document if they are interested in `Advanced installation instructions`.

What I think we should provide is a document that explains step by step:
- How to get Anaconda
- How to set up an environment with pandas
- How to import and possibly show the pandas version
- Link to the tutorials (we are working on them) and to the advanced installation instructions if they want more options

I'm unsure on whether the instructions should show how to get the environment directly in JupyterLab, show first in a Python terminal and then in JupyterLab, or ignore JupyterLab and just show with the Python terminal.

I think it may make sense to have screenshots and make the installation instructions as easy and visual as possible.

For now they should go into our `/doc/` directory, and when we're happy with them, we'll open the PR in pandas.

**Comment by bhuvanakundumani** [comment]
I am interested in working on this issue. Can i take this?

**Comment by smiaa** [comment]
Even I'm interested to work on this., @bhuvanakundumani, can we collaborate
on this?

**Comment by WuraolaOyewusi** [comment]
I think the instructions should include JupyterLab/Notebook Environment too.

**Comment by bhuvanakundumani** [comment]
@smiaa . Sure

**Comment by bhuvanakundumani** [comment]
Sure @smiaa

**Comment by datapythonista** [comment]
There is a small change here. We'll finally have this page in markdown, and not in rst.

Btw, any ETA for this? I'll have a first draft of the new pandas website soon, and would be nice to have an initial version of this page (we can surely keep iterating on improving it later on).

**Comment by datapythonista** [comment]
This comment is also relevant here: https://github.com/python-sprints/pandas-mentoring/issues/119#issuecomment-521366438

**Comment by bhuvanakundumani** [comment]
@datapythonista i will work on this over this weekend and try to finish it

**Comment by smiaa** [comment]
@datapythonista to clarify, do we need to create the markdown pages in
python-sprints repo or python-web repo?

**Comment by datapythonista** [comment]
In pandas-web they already exist, the best is just add the content there.

**Comment by bhuvanakundumani** [comment]
@datapythonista - I went through the install.md in the padas-web repo. Should i update the install.md to have installation instructions from terminal? thanks

**Comment by datapythonista** [comment]
To me it makes sense to give installation instructions as simple as possible for new users, and provide other options in a separate page. I think that's less intimidating for very beginner users.

**Comment by bhuvanakundumani** [comment]
ok.i understand.Thanks

**Comment by smiaa** [comment]
@bhuvana I am not able to work on this issue currenly. FYIP.
