### ISSUE TITLE
New citing and artwork section in the pandas website

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#119]
In the new pandas website, I'd like to have a section for resources to cite pandas. To be specific, I want people to be able to cite pandas in scientific papers, and also to use the pandas logo correctly.

Scikit-learn has something like that in their about us section:
https://scikit-learn.org/stable/about.html#citing-scikit-learn

In the current website we've got two papers in the talks section:
https://pandas.pydata.org/talks.html Not sure which would be the preferred to cite pandas (will check with Wes later to see if he's got a preference).

For the logo, I expect to have different versions (for white background, for black background, with text, without...). Besides providing the svg for them, would be nice to provide some guideliness on how we expect the logo to be used (leaving certain margin, do not distort proportions, do not place text on top...). To give an idea, see the brand guidelines from JetBrains: https://www.jetbrains.com/company/brand/ (most big companies will have one, should be easy to find many other examples).

While we don't have the new logo yet, would be useful to have a first version of this page while building the website (should be very easy to update the logo later and get the final version).

For now the new website should live in this repo, in the `/doc/` directory.

**Comment by martinagvilas** [comment]
Can I work on making a first draft of this page? So that then others can add improvements to it.

**Comment by datapythonista** [comment]
that would be great, thanks @martinagvilas

**Comment by WuraolaOyewusi** [comment]
@martinagvilas  Can we work together on this?

**Comment by martinagvilas** [comment]
@WuraolaOyewusi sure! Would it make sense that I first upload a very simple file (e.g. only with the headers) and we start populating it together after that? We could divide the sections. Or do you have another suggestion?

**Comment by WuraolaOyewusi** [comment]
Ok, upload the file with headers.

**Comment by martinagvilas** [comment]
@WuraolaOyewusi I have uploaded the file with headers [here](https://github.com/python-sprints/pandas-mentoring/blob/master/doc/citing_pandas.md).

What if I work in the citing subsection and you do the artwork one?

**Comment by datapythonista** [comment]
I created a temporary repo for the new pandas website, where I'll have this page initially, while working with the designer: https://github.com/datapythonista/pandas-web/

The website renders automatically after a PR is merged to: https://datapythonista.github.io/pandas-web/ (right now there is not much, and no styles at all, but will keep adding things).

Feel free to send the PR to that repo, or also ok to keep the work here, and I'll move it there once it's done.

**Comment by WuraolaOyewusi** [comment]
@martinagvilas  Ok, I will give a try.

**Comment by martinagvilas** [comment]
@datapythonista ok, I think it's better to work directly on the web repo, so I will try to make the PR there

**Comment by WuraolaOyewusi** [comment]
@martinagvilas . Any update on this? I've made a draft for the logo guidelines

**Comment by martinagvilas** [comment]
@WuraolaOyewusi. As I said a few comments ago, I made the changes directly in the pandas-web repo. You can see them there :)

**Comment by WuraolaOyewusi** [comment]
@martinagvilas , Ok, please can you share a link to it?

**Comment by datapythonista** [comment]
This is the link @WuraolaOyewusi 

As I said in my email, I expected to have all the changes to the website in couple of days, whoever wanted to contribute to it, had to be fast. :)

Now I already opened a PR in pandas itself, feedback is very welcome, you'll have to add it to the PR in pandas directly: https://github.com/pandas-dev/pandas/pull/28014

**Comment by WuraolaOyewusi** [comment]
Oh, Ok @datapythonista .
