### ISSUE TITLE
Copy the documentation about contributing to pandas to this repository

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#12]
There is a directory `doc/source/development` in pandas that contains few files with the documentation on how to contribute. That documentation is kind of all right, and contains useful information, but could be easily improved, and make it easier for anyone to follow (including ourselves).

What we can do is to copy that documentation in this repository, improve it here in an iterative way, and then open a PR in pandas with all the updates.

I think it's probably good to keep these files in the same directory as in pandas here, `doc'/source/development`.

I'd also save somewhere (in a file in the repo, or in a comment to this ticket) the commit of the last version of pandas when copying these files, so we can later see if something changes in pandas while making the changes here. The commit hash can be obtained by simply `git log`.

**Comment by martinagvilas** [comment]
Cool! But I have a very basic question: to copy the documentation files in our repository, should we fork the whole pandas repository? Or is it possible to only fork this specific subdirectory?

**Comment by smiaa** [comment]
How to copy the pandas documentation in this repository? If I fork it, for example, won't it appear under my user?

**Comment by sparalic** [comment]
I took a stab at this using Github's subversion feature to only copy the `dev/source/development` folder, using this solution  I submitted a PR for the branch: https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo

Please let me know if this is what you were asking.

**Comment by datapythonista** [comment]
I'm open to any idea here, but something as simple as cloning the pandas repository independently, and copy the 4 (I think) files of the contributing docs, to this repo, and open a PR with that, is good enough for now. If we do this approach, and we keep an independent copy, then it'd be useful to check which was the version of pandas (last commit hash) of the copied files. This way we will be able to easily see all the changes to those files since we copied them, until we want to merge them back with our changes.

**Comment by sparalic** [comment]
@datapythonista once I clone the repo and copy the files to this repo is it fair to assume that the history will be maintained?

**Comment by datapythonista** [comment]
No, not really, but we probably don't care about the history of those files. What we are doing is useful but a bit hacky. You can just copy them here as if you received them by email. We're going to build a new contributing documentation, and for now we don't care about pandas. But we'll use what's there for convenience. But there won't be any connection between the pandas repo and this one.

**Comment by sparalic** [comment]
@datapythonista. Perfect, these sprints are definitely teaching me git best practices! Thank you again.
