### ISSUE TITLE
DataFrame.to_parquet fails with index parameter

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#123]
This issue should be created in the pandas repo, but creating it here so nobody not in this groups claims it.

**Please consider this before claiming this issue:**
- This is somehow advanced, and besides requiring decent Python/pandas skills, it may require an important amount of time, please don't claim it if you don't have it in the next few days
- If you already made your first PR to pandas, please give priority to someone who didn't (you're always welcome to look for "Good first issues" in pandas, and hopefully I can create enough issues for everyone who wants to work in them soon).
- Feel free to research on this issue, discuss... even if you don't claim it, but better let someone new open the PR and follow the process end to end

See the next example:
```python
>>> import pandas
>>> pandas.DataFrame({'foo': [1, 2], 'bar': [3, 4]}).to_parquet('test.parquet', engine='pyarrow', index=False)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-3a1f9432d201> in <module>()
      1 import pandas
----> 2 pandas.DataFrame({'foo': [1, 2], 'bar': [3, 4]}).to_parquet('test.parquet', engine='pyarrow', index=False)

/opt/anaconda2/envs/markdowna/lib/python3.5/site-packages/pandas/core/frame.py in to_parquet(self, fname, engine, compression, **kwargs)
   1943         from pandas.io.parquet import to_parquet
   1944         to_parquet(self, fname, engine,
-> 1945                    compression=compression, **kwargs)
   1946 
   1947     @Substitution(header='Write out the column names. If a list of strings '

/opt/anaconda2/envs/markdowna/lib/python3.5/site-packages/pandas/io/parquet.py in to_parquet(df, path, engine, compression, **kwargs)
    255     """
    256     impl = get_engine(engine)
--> 257     return impl.write(df, path, compression=compression, **kwargs)
    258 
    259 

/opt/anaconda2/envs/markdowna/lib/python3.5/site-packages/pandas/io/parquet.py in write(self, df, path, compression, coerce_timestamps, **kwargs)
    119             self.api.parquet.write_table(
    120                 table, path, compression=compression,
--> 121                 coerce_timestamps=coerce_timestamps, **kwargs)
    122 
    123     def read(self, path, columns=None, **kwargs):

/opt/anaconda2/envs/markdowna/lib/python3.5/site-packages/pyarrow/parquet.py in write_table(table, where, row_group_size, version, use_dictionary, compression, use_deprecated_int96_timestamps, coerce_timestamps, flavor, **kwargs)
   1090                 compression=compression,
   1091                 use_deprecated_int96_timestamps=use_int96,
-> 1092                 **kwargs) as writer:
   1093             writer.write_table(table, row_group_size=row_group_size)
   1094     except Exception:

/opt/anaconda2/envs/markdowna/lib/python3.5/site-packages/pyarrow/parquet.py in __init__(self, where, schema, flavor, version, use_dictionary, compression, use_deprecated_int96_timestamps, **options)
    309             use_dictionary=use_dictionary,
    310             use_deprecated_int96_timestamps=use_deprecated_int96_timestamps,
--> 311             **options)
    312         self.is_open = True
    313 

/opt/anaconda2/envs/markdowna/lib/python3.5/site-packages/pyarrow/_parquet.pyx in pyarrow._parquet.ParquetWriter.__cinit__()

TypeError: __cinit__() got an unexpected keyword argument 'index'
```

Based on the documentation, with `index=False` the DataFrame should be saved without index. But instead a pyarrow exception is raised.

Tasks to do:
- Verify that in the latest (`master` branch) pandas the problem still exists, and the documentation is still incorrect
- Check if pyarrow support writing without the index (it should), and how
- Use `git blame` to see who is the main contributor(s) to the `to_parquet` functionality
- Open an issue in the pandas repo explaining in detail the problem, and propose your solution; please tag me @datapythonista and also the person who worked more on that part
- Claim the issue immediately after creating it with a comment saying you're working on it
- Wait for confirmation on the approach you're proposing, and when maintainers are happy with it, open a PR with the fix

**Comment by sara-02** [comment]
@datapythonista is this issue related to Python2?
```
~$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> pandas.__version__
'0.25.0'
>>> pandas.DataFrame({'foo': [1, 2], 'bar': [3, 4]}).to_parquet('test.parquet', engine='pyarrow', index=False)
>>> pandas.DataFrame({'foo': [1, 2], 'bar': [3, 4]}).to_parquet('test.parquet', engine='pyarrow', index=True)
>>> import pyarrow
>>> pyarrow.__version__
'0.14.1'
>>> 
```
I just tried it on my system with Python3 and the existing pandas version installed, I did not get any error :/

**Comment by datapythonista** [comment]
Thanks for checking @sara-02 

Looks like in my company they've got an old version of pyarrow, 0.10, didn't realize. Can you downgrade your arrow version to that, and see if with the latest pandas we get that error are a better one?

In the 0.25 release notes, we say that we support pyarrow since 0.9.0. I don't think we want to fix compatibility with old versions, but it's not right that we show the pyarrow exception, we should raise one ours that says something like `To be able to use the index parameter in to_parquet, you require pyarrow >= 0.11` or whatever makes sense. Then users know what's the problem and how to fix it. Or simply increase the version we require. In the step of creating the issue in pandas it's when people who worked on that part more will be able to share what they think it's the best solution.

**Comment by sara-02** [comment]
@datapythonista  I created a virtualenv for Python3 and tested the commands, and did not get any error.
```
(env3) ~/test$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> pandas.__version__
'0.25.0'
>>> import pyarrow
>>> pyarrow.__version__
'0.10.0'
>>> pandas.DataFrame({'foo': [1, 2], 'bar': [3, 4]}).to_parquet('test.parquet', engine='pyarrow', index=False)
>>> pandas.DataFrame({'foo': [1, 2], 'bar': [3, 4]}).to_parquet('test.parquet', engine='pyarrow', index=True)
/home/sarah/test/env3/lib/python3.6/site-packages/pyarrow/pandas_compat.py:114: FutureWarning: A future version of pandas will default to `skipna=True`. To silence this warning, pass `skipna=True|False` explicitly.
result = infer_dtype(pandas_collection)
```

**Comment by datapythonista** [comment]
I guess it's been fixed then, thanks for checking!
