### ISSUE TITLE
Timestamp docstring with missing periods

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#134]
Same as #132, but for some other docstrings.

```
pandas.Timestamp.resolution: Summary does not end with a period
pandas.Timestamp.tz: Summary does not end with a period
pandas.Timestamp.ceil: Summary does not end with a period
pandas.Timestamp.combine: Summary does not end with a period
pandas.Timestamp.floor: Summary does not end with a period
pandas.Timestamp.fromordinal: Summary does not end with a period
pandas.Timestamp.isoweekday: Summary does not end with a period
pandas.Timestamp.replace: Summary does not end with a period
pandas.Timestamp.round: Summary does not end with a period
pandas.Timestamp.weekday: Summary does not end with a period
pandas.Timedelta.ceil: Summary does not end with a period
pandas.Timedelta.floor: Summary does not end with a period
pandas.Timedelta.isoformat: Summary does not end with a period
pandas.Timedelta.round: Summary does not end with a period
```

**Comment by sparalic** [comment]
@datapythonista I can pick up this one as well

**Comment by datapythonista** [comment]
Cool. The list was generated with `./scripts/validate_docstring.py --errors=SS03`, and I created issues for batches of those. If you want to create new issues for errors like this in this report, you can find more info here: https://github.com/pandas-dev/pandas/issues/27977

**Comment by sparalic** [comment]
@datapythonista  will do. Marc, I noticed that I was bouncing around several different sources and piecing together things to get things set-up to simply run this validation script. Would it help if I add some end-to-end instructions from setting ups the pandas env run the validate script all the way to submitting your changes?  Maybe in the lessons learned or contribution md file?

It would combine  these two sets of information:
1. https://python-sprints.github.io/pandas/guide/pandas_pr.html#validate-that-your-docstring-does-not-have-technical-errors

2. Setting up your pandas-dev: https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#contributing-dev-env

**Comment by datapythonista** [comment]
Ideally we would have clear documentation on that in the pandas website itself. In the new website I did a bit of work on splitting the contributing docs, which goes in the direction that you're mentioning.

Feel free to create the document you propose. But it may be worth to wait until the initial PR for the website is merged, and then improve the docs there.

**Comment by sparalic** [comment]
Closes: fix punctuation in Timestamp/Timedelta docstrings #28053 in pandas
