### ISSUE TITLE
DISCUSSION: Commit convention

### ISSUE THREAD

**Issue by galuhsahid** [python-sprints/pandas-mentoring#151]
Hi everyone,

I was wondering if we need to have a convention for commit messages in this repository. Pandas uses a convention for commit message and layout, and I was thinking if we have such convention in this repository, it would get us used to the convention before we contribute to the pandas codebase if we haven't.

This is Pandas' commit convention (source: https://pandas.pydata.org/pandas-docs/stable/development/contributing.html):

```
Here are some common prefixes along with general guidelines for when to use them:

    ENH: Enhancement, new functionality
    BUG: Bug fix
    DOC: Additions/updates to documentation
    TST: Additions/updates to tests
    BLD: Updates to the build process/scripts
    PERF: Performance improvement
    CLN: Code cleanup

The following defines how a commit message should be structured. Please reference the relevant GitHub issues in your commit message using GH1234 or #1234. Either style is fine, but the former is generally preferred:

    a subject line with < 80 chars.
    One blank line.
    Optionally, a commit message body.
```

If we agree to have this convention, we can have this in our [CONTRIBUTING.md](https://github.com/python-sprints/pandas-mentoring/blob/master/contributing.md) file. Looking forward to hear your thoughts on this!

**Comment by galuhsahid** [comment]
If there's no objection, does anyone want to take this issue?

**Comment by martinagvilas** [comment]
Hi! I'm working on this right now :) WIll submit a PR today

**Comment by galuhsahid** [comment]
Done in #154, thank you @martinagvilas!
