### ISSUE TITLE
Generate dashboard for docstring errors

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#152]
We've implemented a notebook that preprocess the data of docstrings known errors, and plots how many we've got: https://github.com/python-sprints/pandas-mentoring/blob/master/notebooks/docstring_error_frequency.ipynb

This is very useful, but I think it'd be even cooler if we convert that notebook to an interactive dashboard that let us easily identify what docstrings need to be fixed.

I'm thinking for example on have ipywidgets with a dropdown with the list of errors, with a list of pandas components (e.g. `Series`, `DataFrame`, others...), and playing with those widgets, be able to select specific docstrings, and be able to see the list of errors to fix, the source code of the docstring (the markdown version) and even a rendered html version.

Not sure how difficult that could be, but I think jupyter has lots of cool stuff for those things nowadays, so I think is doable to get something quite cool.

Much better to do this iteratively, adding one or few things at a time (and may be create other tickets and use this one as the "parent")?

**Comment by sparalic** [comment]
This is a cool idea. I’ll like to give it a shot

**Comment by dujm** [comment]
I would like to join @sparalic. I will learn about the topic in the next days and discuss my plans with you @sparalic @datapythonista

**Comment by sparalic** [comment]
@dujm we can absolutely team up on this, I’ve done most of my dashboards in R. So it’ll be nice to learn how to do it with Dash or plain old widgets in Jupyter.

**Comment by datapythonista** [comment]
if you implement the code as a jupyter notebook, you can use voila to convert it to a dashboard automatically: https://github.com/QuantStack/voila

**Comment by datapythonista** [comment]
Just found out there is a gallery of voila dashboards for inspiration: https://voila-gallery.org/services/gallery/

**Comment by sparalic** [comment]
<img width="980" alt="Screen Shot 2019-08-25 at 11 32 03 PM" src="https://user-images.githubusercontent.com/28490392/63670157-c96b9600-c790-11e9-8f7e-51f3c235f131.png">
@datapythonista and @dujm  I was a bit busy last week, so sorry for the delay. But I used the examples Marc shared to create the first filter. This first draft show all of the errors associated with the selected pandas class. The next step is to add a dropdown for the error codes which generates a list of the actual errors for the selected pandas class. I am thinking of using the table generated from this example for the output of the error code dropdown: 

https://voila-gallery.org/user/seidlr-voila-in--football-pitch-4g8y2eez/voila/render/Interactive-Football-Pitch.ipynb?token=JD5RnWKTQeeeOo9lKi1iow


@datapythonista and @dujm let me know what you think?

**Comment by dujm** [comment]
@sparalic Nice work! I think the next step(s) you planned also make sense. 

I really like the [example](https://voila-gallery.org/user/seidlr-voila-in--football-pitch-4g8y2eez/voila/render/Interactive-Football-Pitch.ipynb?token=JD5RnWKTQeeeOo9lKi1iow) you suggested(`Interactive plot + sortable table`).

I'm just not sure whether it's easy to find a code using `a dropdown of error codes` (maybe sorting codes alphabetically?). However, since we are learning, it's always nice to try different options.

**Comment by datapythonista** [comment]
Thans @sparalic, that looks great.

For the error codes, probably the best is import `scripts/validate_docstrings.py` and get the list from the constant. In a recent version of Python (>= 3.6) you'll get the dictionary sorted. Alphabetical order also makes sense, but that order starts by the global errors, and then lists them based on the order of the sections in the docstrings. But whatever is the order, getting the data from that file instead of hardcoding the values will  keep things updated if we add new errors to the validation (which can happen).

Having a table like in the football example sounds great. Not sure if once an element in the table is clicked the details of the docstring can be shown, but that would be amazing.

@sparalic feel free to open a PR with whatever you have. Reviewing notebooks it's not great, since it's json, but I'm happy to get whatever you submit merged, so we can see the notebook and play with it.

Thanks for the work on this, will be very useful.

**Comment by sparalic** [comment]
@dujm and @datapythonista thank you for the suggestions. I’ve been busy with work. I will set aside time tonight to share what I have so far, so we can collaborate.

**Comment by dujm** [comment]
Hi @sparalic, thanks for the update :)  But no stress if you are busy. Because I had time and was playing with the widgets. I should be able to send a PR today. Look forward to discussing with you and getting your input later.

**Comment by sparalic** [comment]
@datapythonista I will continue to play around with what I’ve done. Do you still want me to create a PR for the work I did on this?

**Comment by datapythonista** [comment]
Sure. It may make sense later to get into a single dashboard the best of all, but not a problem to have more than a dashboard.

**Comment by sparalic** [comment]
@datapythonista sounds great!! We can both experiment and learn and create a single dashboard that merges elements from both of our experiments.

**Comment by dujm** [comment]
Here is the [binder link](https://hub.gke.mybinder.org/user/python-sprints-pandas-mentoring-kdkg9ww1/notebooks/notebooks/docstring_error_interactive.ipynb) of my [notebook](https://github.com/python-sprints/pandas-mentoring/blob/master/notebooks/docstring_error_interactive.ipynb). You could run the interactive widgets.

**Comment by sara-02** [comment]
@dujm @sparalic Can we close this issue now?

**Comment by dujm** [comment]
@sara-02 Hey! I closed it. Thanks for reminding.
