### ISSUE TITLE
Create a website/blog 

### ISSUE THREAD

**Issue by dujm** [python-sprints/pandas-mentoring#159]
Referring what Marc suggested in his last email,
`I think it could be nice if you want to create a website, a blog... to show your work, share what you're learning, and helping other people who can be interested in also contributing to pandas or other open source projects`

I have set up a GitHub Page to host the `pandas-mentoring` repo 
https://python-sprints.github.io/pandas-mentoring/ 

Other suggestions on creating a website/blog are also welcome.

**Comment by galuhsahid** [comment]
Thanks for setting this up @dujm! I think for the next step we shall have a specific directory in this repo to house our blog posts, and maybe we should have a specific blog post template (containing title, date, username etc.). Is there any step that I'm missing/is there any other alternative?

**Comment by datapythonista** [comment]
In case it's useful, GitHub pages comes with Jekyll, a ruby static site generator, and all the pandas devs that blog that I know of, use Pelican, a Python static site generator.

**Comment by dujm** [comment]
Thanks @datapythonista! I will have a detailed look at [Pelican](https://docs.getpelican.com/en/stable/) and then let's discuss @galuhsahid

**Comment by dujm** [comment]
Hello @galuhsahid @datapythonista! Below is a screenshot of our blog (test version). I used Pelican to generate the website.

* Screenshot
![blog-website-screenshot](https://user-images.githubusercontent.com/30461000/64491488-4e62af00-d269-11e9-9cae-0264ad8fcf80.png)

Any suggestions? If not, I plan to upload two directories `blog` and `pelican-themes` to `pandas-mentoring/` and host the blog on `https://python-sprints.github.io/pandas-mentoring`. 

* File structure. 

├── blog
│   ├── Makefile
│   ├── content
│   │   ├── build-website.md
│   │   └── contributing.md
│   ├── output (including html files)
├── pelican-themes
└──── uikit

**Comment by datapythonista** [comment]
Looks great. I think everything can leave in this repo, so feel free to open a PR. For the Pelican theme you may be interested in adding it as a git submodule.

For the output, with the directory structure you propose, if the blog is served directly from github pages, you'd have a url like https://les-pandanistas.org/output/. If another server is used, then the path can be changed.

One option is to have two repos, another one is to output into the root, and there are more, like having a home page, and then render the blog in `blog/` (I did that for my page/blog: https://github.com/datapythonista/datapythonista.github.io)

Up to you, and no problem at all on starting with an option, and changing to a different one if later on we think it's not the best one.

**Comment by dujm** [comment]
Thank you @datapythonista! This is very helpfu! I will try to implement these two points your suggested (theme and output rendering) and open a PR asap.
