### ISSUE TITLE
Add note about diversity to the team page

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#168]
In the new website we added a page to provide information about the pandas team: https://dev.pandas.io/community/team.html Unfortunately, and as you're aware, the team is not very diverse at the moment.

I've been told that it may not be a good thing to show "the wall of dudes".  You'll know better what's the message we're giving, but I guess it's true that the team page can discourage people from other backgrounds.

I was thinking if instead of hiding the problem, if it'd make more sense to add a note immediately after the team, about diversity. Something like "pandas welcomes contributors regardless of gender, race... we know we've got a problem, if you want are from a different background don't feel discouraged, and if you need help please get in touch".

What do you think about it? What would you do? Anyone interested in opening a PR with whatever you think it's better?

**Comment by dorothykiz1** [comment]
@datapythonista hello am a little confused do I add it to pandas,
 if so how do I get the link to the repo? also, I agree with the suggestion it's so needed

**Comment by datapythonista** [comment]
Not sure I understand the question.

You need to fork and clone the pandas repo: https://github.com/pandas-dev/pandas/

And this is the file that needs to be changed: https://github.com/pandas-dev/pandas/blob/master/web/pandas/community/team.md

The file is moved and slightly changed in https://github.com/pandas-dev/pandas/pull/28582, so your changes may conflict when that PR is merged. The conflict should be trivial to fix, so don't let that stop you from making the changes.

Thanks for working on this, and let me know I didn't answer your question

**Comment by sara-02** [comment]
@dorothykiz1 I assume this issue is fixed now, AFAIK the PR is merged.

**Comment by sara-02** [comment]
Fixed in https://github.com/pandas-dev/pandas/pull/28630
