### ISSUE TITLE
Unable to install pandas from source

### ISSUE THREAD

**Issue by martinagvilas** [python-sprints/pandas-mentoring#169]
I'm no longer able to install pandas from source. I followed the installation steps described [here](https://pandas.pydata.org/pandas-docs/stable/development/contributing.html#contributing-to-the-code-base). I'm able to create the `pandas-dev` conda environment successfully, but when I run `python setup.py build_ext --inplace -j 4`, I get the following error:

```
(pandas-dev) ➜  pandas git:(master) python setup.py build_ext --inplace -j 4

Traceback (most recent call last):
  File "setup.py", line 812, in <module>
    ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
  File "setup.py", line 540, in maybe_cythonize
    build_ext.render_templates(_pxifiles)
  File "setup.py", line 126, in render_templates
    pyxcontent = tempita.sub(tmpl)
NameError: name 'tempita' is not defined
```

It seems like tempita is not imported properly.

cc @datapythonista. Let me know if I should move this issue to the pandas repo, or to the gitter channel.

**Comment by datapythonista** [comment]
Can you run `conda env update` from the root directory and retry. Didn't know about tempita, not sure if it's a dependency we just added.

**Comment by martinagvilas** [comment]
It works after running `conda env update`, thanks!
