### ISSUE TITLE
Set up sphinx to build the documentation

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#31]
Once #12 and #17 we should have sphinx set up to be able to convert our markdown documentation into its html version.

Documentation for sphinx is available at: http://www.sphinx-doc.org/en/master/

**Comment by galuhsahid** [comment]
Can I work on this issue? Thank you!

**Comment by datapythonista** [comment]
Please do @galuhsahid :)

**Comment by datapythonista** [comment]
@galuhsahid if you face any problem let me know. Dealing with sphinx is sometimes extremely annoying, don't feel like you need to deal with it by yourself.

**Comment by datapythonista** [comment]
@MKhalusova in general it's a good practice to mention in an issue when you plan to work on something, so other people is aware and there is no repeated work. Not really important in this case, since I'm actually encouraging that everybody works on all issues at the same time, but probably worth to get used to those things anyway.

Also, since @galuhsahid started working on this, probably nice to let her know you're working on it too, and may be work together and share experience where it makes sense (publicly in issues and PRs, we're all part of a team). ;)

**Comment by galuhsahid** [comment]
Closed with #51
