### ISSUE TITLE
Create gitter channel for pandas-mentoring 

### ISSUE THREAD

**Issue by Aya-S** [python-sprints/pandas-mentoring#55]
Create a gitter channel to aid in collaborating on issues among the pandas-mentoring members

**Comment by datapythonista** [comment]
@python-sprints/pandas-mentoring do you think the channel should be public or private? Everybody in the group will be able to join both ways, the difference is whether anyone else could be able to read the messages, join and comment.

I'm happy with whatever you decide.

**Comment by Aya-S** [comment]
I think, as a start, it should be private.

**Comment by dujm** [comment]
How about we try a vote under @datapythonista 's message ? Add a :smile: to vote for public, :eyes: for private?

**Comment by smiaa** [comment]
I think it could be private for now.

**Comment by datapythonista** [comment]
I created the gitter channel, for now it's public, but if the votes change and we want to make it public later, we can easily do that later.

The url is: https://gitter.im/py-sprints/pandas-mentoring

I think people in the @python-sprints/pandas-mentoring organization should be able to join, for the rest not sure if you can request access, or need to be added manually. We'll figure it out, and we'll make sure everybody is there soon.  Ping me if you can't access, and I'll make people admin of the channel, so several people are able to add others.

**Comment by galuhsahid** [comment]
> I created the gitter channel, for now it's public, but if the votes change and we want to make it public later, we can easily do that later.
> 
> The url is: https://gitter.im/py-sprints/pandas-mentoring
> 
> I think people in the @python-sprints/pandas-mentoring organization should be able to join, for the rest not sure if you can request access, or need to be added manually. We'll figure it out, and we'll make sure everybody is there soon. Ping me if you can't access, and I'll make people admin of the channel, so several people are able to add others.

I'm somehow not able to access the channel, it says "404. This is not the chat you're looking for. Sorry. :("

**Comment by datapythonista** [comment]
gitter permissions are not great. I selected a checkbox so anyone in the organization could join, but not sure how it's supposed to work.

I added you (@galuhsahid) and @bhavaniravi as admins of the python-sprints gitter, feel free to add people to the channel, change setting, and make it more efficient for people to join, if you find a way.

**Comment by MKhalusova** [comment]
I followed the url, got 404, clicked on Sign-in. Now, I have an issue with what I see on the Sign-in screen. It says: "This application will be able to read your organization, team membership, and private project boards." 
And the organization it shows is the company I work for, nowhere do I see "pandas-mentoring".
I'm not familiar with gitter and I'm not sure my company would be super happy if I gave access to this app to company's private project boards. Is there a way to join without giving it access to company's private projects?

**Comment by datapythonista** [comment]
That doesn't sound reasonable, but not much idea about that. I don't remember accepting that (may be I just don't have a private organization associated to my github user). Can you access the public channels without accepting that, like pandas?

**Comment by datapythonista** [comment]
I see that you can also sign up with gitlab or twitter, may be that's an option for now?

**Comment by MKhalusova** [comment]
I don't have a gitlab account. I tried with Twitter, and it still ends up asking me to give it access to my company's private repo. I have an idea as to why this may be happening. Perhaps I'm not part of pandas-mentoring organization, so gitter can't find the board, and it ends up trying to look in other private spaces?

**Comment by MKhalusova** [comment]
I think I managed to connect gitter but now I get the same as @galuhsahid had: "404. This is not the chat you're looking for. Sorry. :("
Sigh.

**Comment by smiaa** [comment]
Even I got the same error, I've created an issue for the same.

**Comment by galuhsahid** [comment]
For people who have joined the @python-sprints/pandas-mentoring organization, it seems like you first need to make your membership public by going to https://github.com/orgs/python-sprints/people and change your membership visibility from Private to Public (reference: https://github.com/CHME5137/github-assignment/issues/6)

**Comment by dorothykiz1** [comment]
Hello all
am also getting a 404. This is not the chat you're looking for. Sorry. :( 
Have a suggestion of  us considering  slack too if most of us are familiar with it or we could vote on this

**Comment by datapythonista** [comment]
@dorothykiz1 I invited you to the pandas-mentoring organization, I think that should fix the problem (someone mentioned that you need to make public your membership for gitter).

Probably the best way to discuss about using slack is to create an issue.

Btw, `@ALL` is a GitHub organization from someone else (misleading, I know). You can use `@python-sprints/pandas-mentoring`. It doesn't include everybody in the team yet, but I think it's the best we have (unless you want to tag everybody individually).

**Comment by dorothykiz1** [comment]
Thanks, @datapythonista have edited @all part  and yes seen yo invitation let me see if it lets me in

**Comment by BhagyaC** [comment]
@datapythonista gitter is for limited members ??

**Comment by datapythonista** [comment]
Gitter is public, and our channel is for everybody in this group. But it was decided to make the channel private, and we're still figuring out how to get everybody in in an efficient way. So far we're manually adding people to our GitHub team as someone requests it, and then I think it's already possible to access the channel.

**Comment by asvithajanani** [comment]
Can someone invite me in the @python-sprints/pandas-mentoring organization or add to the gitter channel, someone who has admin access. Do I need to create a separate issue for this?

**Comment by bhavaniravi** [comment]
@datapythonista I just read the whole thread. Still stuck at the 404.

**Comment by BhagyaC** [comment]
@datapythonista then please send me a request to join the organization

**Comment by datapythonista** [comment]
@bhavaniravi you already appear in the gitter channel. In any case I invited the three of you to the organization.

**Comment by bhuvanakundumani** [comment]
@datapythonista Can you please send me a request to join gitter ?

**Comment by sara-02** [comment]
@datapythonista I would like to join the Gitter channel.

**Comment by datapythonista** [comment]
I invited you two to the pandas-mentoring organization. After that you should be able to join the gitter channel. If it's not immediate how to join, someone explained in a GitHub comment, you probably want to add that explanation to the README file, so it's easier to find for everyone else.

**Comment by Ayowolet** [comment]
I have signed in to Gitter, made my membership public but I still get the 404 message. I even searched for pandas-mentoring and tried to join from there... Am I missing something?

**Comment by bhavaniravi** [comment]
Gitter still gives me a 404

**Comment by datapythonista** [comment]
@bhavaniravi can you access the pandas public channel? https://gitter.im/pydata/pandas

**Comment by bhavaniravi** [comment]
@datapythonista yes finally.

**Comment by montjoile** [comment]
Hello, could you add me on glitter? It seems that I don't have any access. 
Thanks!

**Comment by Aya-S** [comment]
@montjoile your GitHub link doesn't seem to be there on the README.md ,if it's not then i guess you should add it to the doc.

**Comment by Aya-S** [comment]
@montjoile I just mentioned you in the chat you were added. Can you confirm if you are able to access the channel?
