### ISSUE TITLE
Add link to gitter channel created in issue #55 to "README.md"

### ISSUE THREAD

**Issue by Aya-S** [python-sprints/pandas-mentoring#56]

**Comment by datapythonista** [comment]
Thanks @Aya-S for creating the issues. If you also add the issue number #55 in the description of the issue, that would not only create a link to easily go there, but will also create a issue in #55 to this one, so anyone reading that issue knows there is another one related.

I think it's common to use:

xref #55 

But how you reference it it's not really important, I think.

**Comment by Aya-S** [comment]
ok, good to know!
will note that in future issues.

**Comment by Aya-S** [comment]
will add : https://gitter.im/py-sprints/pandas-mentoring
to README.md

**Comment by Aya-S** [comment]
It renders fine on my branch but I'm no md expert. Will do the adjustment.
