### ISSUE TITLE
Creating a Contributing.md

### ISSUE THREAD

**Issue by martinagvilas** [python-sprints/pandas-mentoring#58]
Hi! I was wondering if it might be helpful to create a markdown detailing how to contribute to this repository. Maybe this is too meta (creating a contributing guideline to work in a repository that in the end will make changes to the contributing guideline of pandas), but I've seen lots of great advices from Marc and others on how to create better issues or PRs and how to style them, and thought perhaps it would be nice to have these advices written somewhere.

**Comment by martinagvilas** [comment]
Well, now I realize this is something that is also on the wiki. Perhaps I could add these advices there instead of in a separate markdown?

**Comment by sparalic** [comment]
@martinagvilas I think we can add a table of contents, and build sections with different topics ranging from how to get started with your first PR (like @dujm already did) and lessons learned etc. This way we have a one stop shop for all things pandas.

**Comment by datapythonista** [comment]
I'm +1 on having a `CONTRIBUTING.md` in the repo, and not in the wiki (I think I was the one suggesting the wiki initially).

To start it could be as easy as moving the document from @dujm. Then we can keep improving it and adding new things in separate PRs.

**Comment by martinagvilas** [comment]
Great! I will start working on it, using the document from @dujm and adding the suggestions of @sparalic

**Comment by datapythonista** [comment]
Cool. Just in case you haven't seen it, the wiki is already a markdown. If you click on edit, you should be able to see the markdown code of the page.

**Comment by sparalic** [comment]
@martinagvilas I will help you pull out some of the great feedback @datapythonista gave us during our first sprint. Do you want to call this a “best practices” or common gottchas?

**Comment by martinagvilas** [comment]
@sparalic great! Let me upload the markdown template based on the wiki one so we can edit it together. I like both titles, but I think "best practices" will be clearer, specially for non-native english speakers :)
