### ISSUE TITLE
Add .gitignore to the project

### ISSUE THREAD

**Issue by MKhalusova** [python-sprints/pandas-mentoring#59]
Add gitignore and include html files generated with sphynx there.

**Comment by sara-02** [comment]
@MKhalusova @datapythonista Can I take this up?

**Comment by datapythonista** [comment]
absolutely @sara-02, go for it!

It's great to ask, so we coordinate. But at this point feel free to work in anything you want to learn. Even if many people work in the same, and at the end we can only merge a PR, if you are going to learn when working in something, it's surely worth it.
