### ISSUE TITLE
fix the slight typo in markdown in Aya's username addition.

### ISSUE THREAD

**Issue by beingenfa** [python-sprints/pandas-mentoring#68]
Just clean out space in between @Aya-S . Markdown doesn't have space between the link text in square brackets and the link in normal brackets.

**Comment by Aya-S** [comment]
I was checking some of the PRs and this should be fixed when one of the existing PRs gets merged. This is mainly the reason why I didn't create a new PR to fix the issue.

**Comment by Aya-S** [comment]
I will create a PR for this now
