### ISSUE TITLE
Discuss PR review conventions

### ISSUE THREAD

**Issue by Aya-S** [python-sprints/pandas-mentoring#70]
Discuss:
- How many reviews and approvals we want to enforce before a PR is cleared for a merge, if any?
- Should this be enforced through git settings?

**Comment by dujm** [comment]
I would suggest:
 * Two (I like getting a 2nd opinion :) ) 
 * No (To be flexible)

**Comment by datapythonista** [comment]
If two reviewers means one approving, and the second can merge, what @dujm proposes is what pandas is currently doing.

**Comment by WuraolaOyewusi** [comment]
I agree with @dujm .

**Comment by sparalic** [comment]
I agree:
Two approves: 1 approve and 1 merge
No: I am not a fan of enforcing strict rules (hehe), of course unless needed

**Comment by datapythonista** [comment]
I think there is agreement in this ticket, can someone write the final convention in the `README` file or somewhere else?

**Comment by sara-02** [comment]
Hey @Aya-S we usually wait for the PR to get merged before closing an issue.
