### ISSUE TITLE
Copy alternative pandas setup instructions

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#74]
In #41, we added the official pandas documentation for contributing.

A bit more than a year ago, we organized a [worldwide pandas sprint](https://python-sprints.github.io/pandas/) to improve the documentation, and since the pandas official documentation wasn't great for beginners, we built an alternative page on how to set up the pandas development environment.

This documentation should be used, or at least considered, when improving the official pandas contributing pages. For now, this issue is only about moving the document to this repo (inside `/doc/source/`, but probably separate from the `development` one, so things don't get mixed).

This is the document:  https://raw.githubusercontent.com/python-sprints/python-sprints.github.io/master/pandas/guide/_sources/pandas_setup.rst.txt?_sm_au_=iVVfbnLZnRjK7PVH (the html version is available [here](https://python-sprints.github.io/pandas/guide/pandas_setup.html))

**Comment by Ayowolet** [comment]
I'd like to attempt this

**Comment by Ayowolet** [comment]
HI @datapythonista I'm sorry I haven;t been able to do this but I'll try to get it sorted tomorrow. I hope that's not too late... Thanks

**Comment by Ayowolet** [comment]
I have tried to add the document on this PR #92

**Comment by Ayowolet** [comment]
Should the html file be added too? I would like to close this issue

**Comment by datapythonista** [comment]
@Ayowolet in general what we do is at the beginning of the PR that closes an issue, we add the text `Closes #74`. This way, the PR and the issue are referenced since the PR is opened and when the PR is merged, github automatically closes the issue.

I don't think we want the html, in general auto-generated files are not included in repos.

**Comment by Ayowolet** [comment]
Thank you @datapythonista. I’ll remember to do that moving on. I wasn’t sure the PR would be fine that’s why I didn’t reference the issue.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
