### ISSUE TITLE
Add link to the new learning points page from the README

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#75]
We recently added this document: https://github.com/python-sprints/pandas-mentoring/blob/master/LEARNING_POINTS.md

It's probably worth to add a link to it from the README file.

**Comment by sparalic** [comment]
@datapythonista I’ll work on this later today

**Comment by martinagvilas** [comment]
Shouldn't we also add these learning points into the contributing.md? In the end they are about how to make better PRs and issues. What do you think? Another possibility is that instead of adding them all to the contributing.md we could link to this document from there as well.

**Comment by sparalic** [comment]
@martinagvilas, that's what I was trying to get a pulse on in my earlier message about duplication. But, I think @datapythonista thinks it might be better to keep them separated as it doesn't really matter at this point. Perhaps, we just make a section in the contributions file and add the contents of  this file (learning.md )to that section? Lmk

**Comment by datapythonista** [comment]
No preference, I think it can make sense to have everything together. But also probably not a bad idea to have a formal document on how to do things, and also a "board" where people can share more informally what they're learning, whether is about git tricky things, pandas, organizational things, friendship, burn out, or whatever.

**Comment by galuhsahid** [comment]
I personally think it's better to have a specific document for learning points and keep the two (learning_points.md and contributing.md) separate, because as we progress we're going to learn more things outside of the scope of contributions. But yes, I do agree that all learning points related to contributions can be added to contributing.md - it can be very helpful for everyone contributing :)

**Comment by martinagvilas** [comment]
What @galuhsahid said makes total sense, +1 to that
