### ISSUE TITLE
Error accessing gutter chanel

### ISSUE THREAD

**Issue by smiaa** [python-sprints/pandas-mentoring#84]
After signing up into gitter using GitHub and granting access to repo, getting this error.
"404. This is not the chat you're looking for. Sorry. :("

**Comment by galuhsahid** [comment]
I've added you to the Gitter channel - can you please check again and let us know if you can access it?

**Comment by Aya-S** [comment]
This will be the case for all of us who are not members of "python-sprints".I'm in the same position and I think only a few people have the needed permissions.
Can you please add us all as members? @galuhsahid

**Comment by galuhsahid** [comment]
I'd be happy to do so! However I'm not sure if it's OK to just add people instead of them opting to do so, though. Anyone has any thoughts on this?

**Comment by smiaa** [comment]
It worked for now. Thanks!!

**Comment by Aya-S** [comment]
@galuhsahid  ok fair enough, maybe we should send an email asking people to opt-in and you then you can add whoever responds positively? how does that sound like to you?

**Comment by galuhsahid** [comment]
@Aya-S That's a great idea - I think it will also raise visibility to the Gitter channel as well. I'll go ahead with that :) thanks!

**Comment by rsdpyenugula** [comment]
Same here I am getting an error when I hit the link. Can you add me and also Why not Slack?
