### ISSUE TITLE
Add learning points related to creating PRs and issues to the contributing.md

### ISSUE THREAD

**Issue by martinagvilas** [python-sprints/pandas-mentoring#89]
I could work on adding to the contributing.md the learning points related to PRs and issues creations (as discussed in #75 ).

What do you think?

**Comment by sparalic** [comment]
@martinagvilas , I like this idea, maybe we can keep it high level with steps 1-7. Basically, just capturing the “how to” basics of contributing(PRs, cloning, forking) and add a link to the learning markdown for more specific topics(sort of a common gotchas while getting starters)? I agree with @galuhsahid keeping them separate serves two very different purposes.

**Comment by martinagvilas** [comment]
sounds like a good idea!

**Comment by Aya-S** [comment]
Hi Girls ! @martinagvilas @sparalic  @galuhsahid ,
is there more work pending related to this issue?

**Comment by martinagvilas** [comment]
Hey @Aya-S I was waiting to see if the LEARNING_POINTS.md got more populated to add the relevant points, but for now I will now add a simple link at the bottom of the page directing to the whole file.
