### ISSUE TITLE
structuring the LEARNING_POINTS.md document

### ISSUE THREAD

**Issue by asvithajanani** [python-sprints/pandas-mentoring#90]
How about structuring it based on topics like git, environment setup etc? Or just listing it for now and grouping it at later point?

**Comment by sara-02** [comment]
We just follow the simple structure of 
Author name: 
  points learned.

That way we can have a section about what each one learned/is learning.
Regrouping according to topic while looks neat, might be difficult for newcomers to maintain.

**Comment by sara-02** [comment]
If the idea looks good, I send a PR for it.

**Comment by WuraolaOyewusi** [comment]
@sara-02  The idea looks good.

**Comment by sara-02** [comment]
Cool, I'll send the PR over the weekend.
