### ISSUE TITLE
Create a slack Channel for the Pandas-mentoring for easy communication

### ISSUE THREAD

**Issue by dorothykiz1** [python-sprints/pandas-mentoring#94]

**Comment by datapythonista** [comment]
I don't think a decision has been made regarding that. Can you clarify that in the title/description of the issue?

**Comment by sara-02** [comment]
@dorothykiz1 Are you facing issues with joining Gitter?

**Comment by dujm** [comment]
Hi @dorothykiz1, I have closed this issue since I believe most of us are on Gitter. Feel free to re-open an issue if you later still would like to set up a slack channel for us.
