### ISSUE TITLE
Not able to JOIN GITTER?? can we use slack for better coordination

### ISSUE THREAD

**Issue by BhagyaC** [python-sprints/pandas-mentoring#98]
Hey all since many having issue (including myself ) to join the gitter channel for our discussion and there is a proper solution for the same. In that case can we choose slack as a better way of discussion and from my side that will be much easier

**Comment by datapythonista** [comment]
I think this is a duplicate of #94.

@BhagyaC I added you to the gitter channel.

**Comment by BhagyaC** [comment]
Sorry I missed that
@datapythonista
