### ISSUE TITLE
Add link to the pandas code of conduct in the README file

### ISSUE THREAD

**Issue by datapythonista** [python-sprints/pandas-mentoring#99]
The pandas `README` file provides a short section about contributing to the project: https://github.com/pandas-dev/pandas#contributing-to-pandas-

While pandas has a strict code of conduct to make sure no sort of harassment or discrimination happens in the project development, there is no reference of link in that section. The code of conduct is in: https://github.com/pandas-dev/pandas/blob/master/.github/CODE_OF_CONDUCT.md

I think it's worth to add a reference and a link to the code of conduct in that section.

Please make sure to comment in this issue if you want to work on this, and make sure that you don't work on this if someone else already started. Also, please tag me when open the PR in pandas.

**Comment by sparalic** [comment]
@datapythonista I can take this one

**Comment by sparalic** [comment]
@datapythonista  when I tried pushing the updates to pandas I get a 403 error. Do I need specific permissions to push to the pandas repo? Or am I missing something?

**Comment by sara-02** [comment]
@sparalic did you by mistake push a change directly to the pandas-dev master instead of the branch on your fork?
What is the result of your `git remote -v`

**Comment by datapythonista** [comment]
> @datapythonista when I tried pushing the updates to pandas I get a 403 error. Do I need specific permissions to push to the pandas repo? Or am I missing something?

You should contribute in the same way you contribute to this repo, openinig PRs. We're like 15 people who has permissions to push to pandas, and there are around 1,500 contributors. And even the people with push permissions we never push to the repo (no exceptions), we always contribute using PRs like the rest (we only use the permissions to merge PRs, after they've been reviewed by enough people).

**Comment by sparalic** [comment]
@sara-02 and @datapythonista when I tried to fork the first time, it said you already have a forked copy i.e. the panda-sprints copy. So I figured I would work off of that fork, but did not work. It's fine now, lesson learned.

@datapythonista I created the pull request : add Code of Conduct ref to README #27780

**Comment by datapythonista** [comment]
cool, as @sara-02 said, `git remote -v` will give you more information on which repos you're interacting with. You want to have `origin` pointing at your fork, and `upstream` pointing at the original repo.

Next time it's probably easier if you tag me directly in the description of the PR when you open it. That way other core devs also have context on where it is coming from.

**Comment by datapythonista** [comment]
I think this has already been merge, feel free to close this issue and refer to the PR once you're ready.

**Comment by sparalic** [comment]
closes #27851 (pandas)
